name: Lint
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install NPM Packages
      run: npm ci

    - name: Lint
      run: npm test

    - name: Update Contributor Image Cache
      if: ${{ github.event.pull_request.merged == true }}
      run: |
        curl -X PURGE "https://contributors-img.firebaseapp.com/image?repo=csprite/languages&max=100000"
