name: Lint
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python
      run: |
        sudo apt-get update -y
        sudo apt-get install python3 -y

    - name: Lint Languages Files
      run: |
        echo "$(python3 ValidateLangFiles.py)" >> "$GITHUB_OUTPUT"

    - name: Update Contributor Image Cache
      if: ${{ github.event.pull_request.merged == true }}
      run: |
        curl -X PURGE "https://contributors-img.firebaseapp.com/image?repo=csprite/languages&max=100000"
